services:
  php_fpm:
    image: php:fpm-alpine3.20
    volumes:
      - ./:/var/www/html
  webserver:
    image: nginx:stable-perl
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html/public